### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by Grungeby52** [zgojcic/3D_multiview_reg#13]
Hi,
When I use my data-set (extract_data.py) ,

python ./scripts/extract_data.py \
			--source_path ./data/train_data/ \
			--target_path ./data/train_data/ \
			--dataset 3d_match \
			--model ./pretrained/fcgf/model_best.pth \
			--voxel_size 0.025 \
			--n_correspondences 20000 \
			--inlier_threshold 0.05 \
			--extract_features \
			--extract_correspondences \
			--extract_precomputed_training_data \
			--with_cuda \

 it creates "correspond and features" but afterwards I get this error.

Traceback (most recent call last):
  File "./scripts/extract_data.py", line 373, in <module>
    args.target_path, args.inlier_threshold, args.voxel_size)
  File "./scripts/extract_data.py", line 254, in extract_precomputed_training_data
    xs = data['xs']
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 266, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'xs is not a file in the archive'

What is the reason of this?

Best Regards

**Comment by zgojcic** [comment]
Hello,

thanks for this opening this issue, there is indeed a typo in the line L254 of the extract_data.py it should be:       ` xs = data['x']`.

I will update the code when I do a full multi-view update today or tomorrow

Best
Zan

**Comment by Grungeby52** [comment]
Hi,

When I run train.py "python3 train.py ./configs/pairwise_registration/train/OANet.yaml" Doesn't enter the For Loop(line 103  'for batch in train_loader:') 
But I have extracted FCGF feature descriptors, established the correspondences, and save trained data

When print train_loader
train_loader = <torch.utils.data.dataloader.DataLoader object at 0x7f49254d1a90>

What is the problem? 

Best Regards
Onur Güzeldemirci
