### ISSUE TITLE
Question on new release of the multiview 3D point cloud registration part

### ISSUE THREAD

**Issue by springslx** [zgojcic/3D_multiview_reg#19]
Hello, thanks for the current release. I have finished the demo part and got a perfect pairwise registration result. But the current release only supports training the pairwise registration network, and is it possible to update the new release on the multiview 3D point cloud registration part not only for the pairwise?

**Comment by scutan90** [comment]
Yes, please open source the multi-view registration code, thank you

**Comment by 1351269957** [comment]
> Hello, thanks for the current release. I have finished the demo part and got a perfect pairwise registration result. But the current release only supports training the pairwise registration network, and is it possible to update the new release on the multiview 3D point cloud registration part not only for the pairwise?

Hello,
  when I run "python ./scripts/pairwise_demo.py", I got the error "ValueError: only one element tensors can be converted to Python scalars".Realize that you have finished the demo part，I would like to ask if you have encountered the same mistake, and how did you solve it.
  Thank you very much

**Comment by springslx** [comment]
> > Hello, thanks for the current release. I have finished the demo part and got a perfect pairwise registration result. But the current release only supports training the pairwise registration network, and is it possible to update the new release on the multiview 3D point cloud registration part not only for the pairwise?
> 
> Hello,
> when I run "python ./scripts/pairwise_demo.py", I got the error "ValueError: only one element tensors can be converted to Python scalars".Realize that you have finished the demo part，I would like to ask if you have encountered the same mistake, and how did you solve it.
> Thank you very much

This is probably caused by the use of a function in the source code. Can you upload the error prompt of the command line and let me have a look？

**Comment by 1351269957** [comment]
> > > Hello, thanks for the current release. I have finished the demo part and got a perfect pairwise registration result. But the current release only supports training the pairwise registration network, and is it possible to update the new release on the multiview 3D point cloud registration part not only for the pairwise?
> > 
> > 
> > Hello,
> > when I run "python ./scripts/pairwise_demo.py", I got the error "ValueError: only one element tensors can be converted to Python scalars".Realize that you have finished the demo part，I would like to ask if you have encountered the same mistake, and how did you solve it.
> > Thank you very much
> 
> This is probably caused by the use of a function in the source code. Can you upload the error prompt of the command line and let me have a look？

Thank you for your timely answer！The error is as follow
Traceback (most recent call last):
  File "./scripts/pairwise_demo.py", line 213, in <module>
    main(cfg, args, logger)
  File "./scripts/pairwise_demo.py", line 142, in main
    data = prepare_data(point_cloud_files, cfg['misc']['voxel_size'])
  File "./scripts/pairwise_demo.py", line 79, in prepare_data
    xyz0 = xyz0[sel0,:]
ValueError: only one element tensors can be converted to Python scalars

**Comment by 1351269957** [comment]
> > > Hello, thanks for the current release. I have finished the demo part and got a perfect pairwise registration result. But the current release only supports training the pairwise registration network, and is it possible to update the new release on the multiview 3D point cloud registration part not only for the pairwise?
> > 
> > 
> > Hello,
> > when I run "python ./scripts/pairwise_demo.py", I got the error "ValueError: only one element tensors can be converted to Python scalars".Realize that you have finished the demo part，I would like to ask if you have encountered the same mistake, and how did you solve it.
> > Thank you very much
> 
> This is probably caused by the use of a function in the source code. Can you upload the error prompt of the command line and let me have a look？

Thank you for your timely answer！The error is as follow
Traceback (most recent call last):
  File "./scripts/pairwise_demo.py", line 213, in <module>
    main(cfg, args, logger)
  File "./scripts/pairwise_demo.py", line 142, in main
    data = prepare_data(point_cloud_files, cfg['misc']['voxel_size'])
  File "./scripts/pairwise_demo.py", line 79, in prepare_data
    xyz0 = xyz0[sel0,:]
ValueError: only one element tensors can be converted to Python scalars

**Comment by 1351269957** [comment]
> > > Hello, thanks for the current release. I have finished the demo part and got a perfect pairwise registration result. But the current release only supports training the pairwise registration network, and is it possible to update the new release on the multiview 3D point cloud registration part not only for the pairwise?
> > 
> > 
> > Hello,
> > when I run "python ./scripts/pairwise_demo.py", I got the error "ValueError: only one element tensors can be converted to Python scalars".Realize that you have finished the demo part，I would like to ask if you have encountered the same mistake, and how did you solve it.
> > Thank you very much
> 
> This is probably caused by the use of a function in the source code. Can you upload the error prompt of the command line and let me have a look？

Thanks for your reply again, I have solved the error now,which is a version error about MinkowskiEngine.

**Comment by 1351269957** [comment]
> > > Hello, thanks for the current release. I have finished the demo part and got a perfect pairwise registration result. But the current release only supports training the pairwise registration network, and is it possible to update the new release on the multiview 3D point cloud registration part not only for the pairwise?
> > 
> > 
> > Hello,
> > when I run "python ./scripts/pairwise_demo.py", I got the error "ValueError: only one element tensors can be converted to Python scalars".Realize that you have finished the demo part，I would like to ask if you have encountered the same mistake, and how did you solve it.
> > Thank you very much
> 
> This is probably caused by the use of a function in the source code. Can you upload the error prompt of the command line and let me have a look？

Thanks for your reply again, I have solved the error now,which is a version error about MinkowskiEngine.

**Comment by springslx** [comment]
> > > > Hello, thanks for the current release. I have finished the demo part and got a perfect pairwise registration result. But the current release only supports training the pairwise registration network, and is it possible to update the new release on the multiview 3D point cloud registration part not only for the pairwise?
> > > 
> > > 
> > > Hello,
> > > when I run "python ./scripts/pairwise_demo.py", I got the error "ValueError: only one element tensors can be converted to Python scalars".Realize that you have finished the demo part，I would like to ask if you have encountered the same mistake, and how did you solve it.
> > > Thank you very much
> > 
> > 
> > This is probably caused by the use of a function in the source code. Can you upload the error prompt of the command line and let me have a look？
> 
> Thanks for your reply again, I have solved the error now,which is a version error about MinkowskiEngine.

OK.

**Comment by springslx** [comment]
> > > > Hello, thanks for the current release. I have finished the demo part and got a perfect pairwise registration result. But the current release only supports training the pairwise registration network, and is it possible to update the new release on the multiview 3D point cloud registration part not only for the pairwise?
> > > 
> > > 
> > > Hello,
> > > when I run "python ./scripts/pairwise_demo.py", I got the error "ValueError: only one element tensors can be converted to Python scalars".Realize that you have finished the demo part，I would like to ask if you have encountered the same mistake, and how did you solve it.
> > > Thank you very much
> > 
> > 
> > This is probably caused by the use of a function in the source code. Can you upload the error prompt of the command line and let me have a look？
> 
> Thanks for your reply again, I have solved the error now,which is a version error about MinkowskiEngine.

OK. Congratulations.

**Comment by wmrenr** [comment]
> > > > Hello, thanks for the current release. I have finished the demo part and got a perfect pairwise registration result. But the current release only supports training the pairwise registration network, and is it possible to update the new release on the multiview 3D point cloud registration part not only for the pairwise?
> > > 
> > > 
> > > Hello,
> > > when I run "python ./scripts/pairwise_demo.py", I got the error "ValueError: only one element tensors can be converted to Python scalars".Realize that you have finished the demo part，I would like to ask if you have encountered the same mistake, and how did you solve it.
> > > Thank you very much
> > 
> > 
> > This is probably caused by the use of a function in the source code. Can you upload the error prompt of the command line and let me have a look？
> 
> Thanks for your reply again, I have solved the error now,which is a version error about MinkowskiEngine.

Which version of  MinkowskiEngine do you use?
